spring.jpa:
  database: postgresql
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-54-234-13-16.compute-1.amazonaws.com/d6sd3rquojsen2
  username: noqalybbjecgbg
  password: 5a25285f2865f86d410dfb469f6112746b80bbe9dc35a67348ad794f4ebb3624
  platform: postgres
  driver-class-name: org.postgresql.Driver


jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 31 days
  token:
    expired-time-ms: 2592000000