spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-54-200-216.compute-1.amazonaws.com/d48dtavg5kaem8
  username: ntrplohdpmgmwg
  password: 151598eac9ecea9fcb599d3ec6c6bc4f551f6f2b96e5ec600c8c13e7f00482c9
  platform: postgres
  driver-class-name: org.postgresql.Driver
