spring.jpa:
  database: postgresql
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-7-132-25.compute-1.amazonaws.com/d20kuds6pbjp8c
  username: qtdfmhevxajygp
  password: 67a7dc0bf7bcb33ff33e7c09f8a5722bfa7b8b4af7a62c925d658ecf4d6cbae9
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 31 days
  token:
    expired-time-ms: 2592000000